name: Build

on:
  pull_request:
    paths:
      - "go/**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
            go-version: "1.24"

      - name: Download dependencies
        working-directory: go
        run: go mod download

      - name: Verify dependencies
        working-directory: go
        run: go mod verify

      - name: Build
        working-directory: go
        run: go build